name: Django CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "^3.10.x"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create a virtual environment
        run: python -m venv venv

      - name: Activate the virtual environment
        run: source venv/bin/activate

      - name: Install Dependencies
        working-directory: ./backend/
        run: |
          pip install --upgrade pip
      #     pip install -r requirements.txt

      # - name: Run Tests
      #   working-directory: ./backend/
      #   run: |
      #     python manage.py test
